<?php

/**
* Implementation of hook_node_info()
*/
function ovp_node_info() {
  return array(
    'ovp' => array(
      'name' => t('Open video player'),
      'module' => 'ovp',
      'description' => "Embed a streaming video.",
    )
  );
}

/**
* Implementation of hook_perm()
 */
function ovp_perm() {
  return array('create ovp', 'edit own ovp');
}

/**
 * Implementation of hook_access()
 */
function ovp_access($op, $node, $account) {
  if ($op == 'create') {
    // Only users with permission to do so may create this node type.
    return user_access('create ovp', $account);
  }

  // Users who create a node may edit or delete it later, assuming they have the
  // necessary permissions.
  if ($op == 'update' || $op == 'delete') {
    if (user_access('edit own ovp', $account) && ($account->uid == $node->uid)) {
      return TRUE;
    }
  }
}

/**
 * Implementation of hook_form()
 */
function ovp_form(&$node) {
  $type = node_get_types('type', $node);

  // We need to define form elements for the node's title and body.
  $form['title'] = array(
    '#type' => 'textfield',
    '#title'=> check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#weight'=> -5
  );

  $form['body_filter']['body'] = array(
    '#type' => 'textarea',
    '#title' => check_plain($type->body_label),
    '#default_value' => $node->body,
    '#required' => FALSE
  );
  $form['body_filter']['filter'] = filter_form($node->format);

  $form['location'] = array(
    '#type' => 'textfield',
    '#title' => t('Streaming location'),
    '#default_value' => isset($node->location) ? $node->location : '',
  );

  return $form;
}

/**
 * Implementation of hook_insert()
 */
function ovp_insert($node) {
  db_query("INSERT INTO {ovp} (vid, nid, location) VALUES (%d, %d, '%s')", $node->vid, $node->nid, $node->location);
}

/**
 * Implementation of hook_update()
 */
function ovp_update($node) {
  // if this is a new node or we're adding a new revision,
  if ($node->revision) {
    ovp_insert($node);
  }
  else {
    db_query("UPDATE {ovp} SET location = '%s' WHERE vid = %d", $node->location, $node->vid);
  }
}

/**
 * Implementation of hook_delete()
 */
//function ovp_delete

/**
 * Implementation of hook_help()
 */
function ovp_help($path, $arg) {
  switch ($path) {
  case 'admin/help#block':
    return '<p>'. t('This creates a content type which allows the creation of streaming video files. These files will be replaced by a player.') . '</p>';
  }
}

function ovp_admin() {
  $form = array();

  $form['ovp_width'] = array(
    '#type' => 'textfield',
    '#title' => t('Width of player'),
    '#default_value' => variable_get('ovp_width', 340),
    '#size' => 3,
    '#maxlength' => 3,
    '#description' => t("The width of the player"),
    '#required' => TRUE,
  );
  
  return system_settings_form($form);
}

function ovp_menu() {
  $items = array();

  $items['admin/settings/ovp'] = array(
    'title' => 'Open video player module settings',
    'description' => 'Here you can change the default settings of the open video player',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ovp_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
