<?php

/**
* Implementation of hook_node_info()
*/
/*function streaming_video_node_info() {
  return array(
    'streaming_video' => array(
      'name' => t('Streaming video'),
      'module' => 'streaming_video',
      'description' => "Embed a streaming video.",
    )
  );
}*/

/**
* Implementation of hook_perm()
 */
function streaming_video_perm() {
  return array('create streaming_video', 'edit own streaming_video');
}

/**
 * Implementation of hook_init()
 */
function streaming_video_init() {
  $path = drupal_get_path('module', 'streaming_video');
  $path .= "/swfobject/swfobject.js";
  drupal_add_js($path, 'module');
}

/**
 * Implementation of hook_filter()
 */
function streaming_video_filter($op, $delta = 0, $format = -1, $text = '') {
  if ($op == 'list') {
    return array(
      0 => t('Substitute ovp'),
    );
  }

  switch ($delta) {
    case 0:

      switch ($op) {
        case 'description':
          return t('Embeds an open video player');

        case 'prepare':
          return $text;

        case 'process':
          $pattern = '/\[ovp:([A-Za-z:\/0-9._-]*)]/';
          $replacement = "";
          //$replacement = "this is my replacement for the text";
          $num_matches = preg_match( $pattern, $text, $matches );
          $location = $matches[1];

          $embed = streaming_video_header_js( $location );

          $replace_me = "<script type='text/javascript'>$embed</script><div id='myPlayerGoesHere'><a href='http://www.adobe.com/go/getflashplayer'><img src='http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif' alt='Get Adobe Flash player' /></a></div>";
          //drupal_add_js( $embed, 'inline');
          $text = preg_replace($pattern, $replace_me , $text);

        default:
          return $text;

        }
      break;
  }
}

function streaming_video_header_js( $src, $options=NULL ) {
  $player = base_path() . "sites/all/libraries/ovp/AkamaiMultiPlayerExample.swf";
  if(!isset($options)) {
    $options = array(
      'autostart' => 'true',
      'themeColor' => '0395d3',
      'mode' => 'sidebyside',
      'scaleMode' => 'fit',
      'frameColor' => '333333',
      'fontColor' => 'cccccc',
      'link' => '',
      'embed' => '',
      'allowFullScreen' => 'true',
      'id' => 'myPlayer',
      'name' => 'myPlayer',
      'width' => '640',
      'height' => '480',
    );
  }

  $embed = "var flashvars = {src: '$src',autostart: '$options->autostart',themeColor: '0395d3',mode: 'sidebyside',scaleMode: 'fit',frameColor: '333333',fontColor: 'cccccc',link: '',embed: ''};var params = {allowFullScreen: 'true'};var attributes = {id: 'myPlayer',name: 'myPlayer'};swfobject.embedSWF('$player', 'myPlayerGoesHere', '640', '480', '9.0.0', 'expressInstall.swf', flashvars, params, attributes);";

  return $embed;
}
