<?php
// $Id: streamingvideo_button.module,v 1.5 2009/08/24 20:48:05 joachim Exp $

/**
 * @file
 * Columns input filter: use <!--column--> to create a column break.
 * Must be placed after the HTML filter and above the line break converter filter:
 *  - HTML filter
 *  - Columns filter
 *  - Line break converter
 * You are strongly advised to override this module's CSS to provide a gutter:
 * this is not cleanly possible with percentage widths.
 */

/**
 * Implementation of hook_wysiwyg_include_directory().
 * @param string $type
 *   Contains either "plugins" or "editors"?
 * @return string
 *   The function returns the include directory "plugins". This directory must only
 *   contain wysiwyg api integration files.
 */
function streamingvideo_button_wysiwyg_include_directory($type) {
  if ($type == 'plugins') {
    return $type;
  }
}
// vim: set filetype=php:
