<?php

/**
* Implementation of hook_node_info()
*/
/*function streaming_video_node_info() {
  return array(
    'streaming_video' => array(
      'name' => t('Streaming video'),
      'module' => 'streaming_video',
      'description' => "Embed a streaming video.",
    )
  );
}*/

/**
* Implementation of hook_perm()
 */
function streaming_video_perm() {
  return array('create streaming_video', 'edit own streaming_video');
}

/**
 * Implementation of hook_init()
 */
function streaming_video_init() {
  $path = drupal_get_path('module', 'streaming_video');
  $path .= "/swfobject/swfobject.js";
  drupal_add_js($path, 'module');
}

/**
 * Implementation of hook_filter()
 */
function streaming_video_filter($op, $delta = 0, $format = -1, $text = '') {
  if ($op == 'list') {
    return array(
      0 => t('Substitute ovp'),
    );
  }

  switch ($delta) {
    case 0:

      switch ($op) {
        case 'description':
          return t('Embeds an open video player');

        case 'prepare':
          return $text;

        case 'process':
          $pattern = '/\[ovp:([A-Za-z:\/0-9._-]*)]/';
          $replacement = "";
          //$replacement = "this is my replacement for the text";
          $num_matches = preg_match( $pattern, $text, $matches );
          $location = $matches[1];
          $player = base_path() . "sites/all/libraries/ovp/AkamaiMultiPlayerExample.swf";
          $embed = "<script type='text/javascript'>var flashvars = {src: '$location',autostart: 'true',themeColor: '0395d3',mode: 'sidebyside',scaleMode: 'fit',frameColor: '333333',fontColor: 'cccccc',link: '',embed: ''};var params = {allowFullScreen: 'true'};var attributes = {id: 'myPlayer',name: 'myPlayer'};swfobject.embedSWF('$player', 'myPlayerGoesHere', '320', '240', '9.0.0', 'expressInstall.swf', flashvars, params, attributes);</script><div id='myPlayerGoesHere'><a href='http://www.adobe.com/go/getflashplayer'><img src='http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif' alt='Get Adobe Flash player' /></a></div>";
          $text = preg_replace($pattern, $embed , $text);

        default:
          return $text;

        }
      break;
  }
}
