<?php
// $Id:$
// This is based off of the streamingvideo_button module
/**
 * @file
 * Makes TinyMCE Templates available as plugin for client-side editors integrated via
 * Wysiwyg API.
 */

/**
 * Implementation of hook_wysiwyg_plugin().
 */
function streamingvideo_button_wysiwyg_plugin($editor, $version) {
  static $integrated = array();

  switch ($editor) {
    case 'tinymce':
      // get values defined on settings page
      // Currently not going to use a settings page (Cary)
      //$jspath = variable_get('streamingvideo_button_path', 'sites/all/files');
      //$jsfile = variable_get('streamingvideo_button_file', 'templates.js');
      $jspath = 'sites/all/files'; // Cary- this needs to change
      $jsfile = 'templates.js'; // Cary - this needs to change
      // include path to js file
      /*
      $settings = array(
        'template' => array('template_external_list_url' => base_path() . $jspath . '/' . $jsfile),
      );
      drupal_add_js($settings, 'setting');
      */
      $tinymce = wysiwyg_get_editor($editor);
      return array(
        'template' => array(
          'path' => $tinymce['library path'] .'/plugins/template',
          'buttons' => array('template' => t('Insert templates')),
          'url' => 'http://wiki.moxiecode.com/index.php/TinyMCE:Plugins/template',
          'internal' => TRUE,
          'options' => array(
            'template_external_list_url' => base_path() . $jspath . '/' . $jsfile,
          ),
          'load' => TRUE,
        ),
      );
  }
}

/**
 * Implementation of hook_menu().
 */
 // Not implementing this (as of now)
/*function streamingvideo_button_menu() {
  $items = array();

  $items['admin/settings/streamingvideo_button'] = array(
    'title' => 'Streaming video button',
    'description' => 'Streaming video button plugin settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('streamingvideo_button_admin_settings'),
    'access arguments' => array('administer filters'),
  );

  return $items;
}
*/

/**
 * Implementation of hook_menu().
 */
 // Not implementing this (as of now)
/*function streamingvideo_button_admin_settings() {
  $form = array();
  
  $form['streamingvideo_button_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Path to your js file'),
    '#default_value' => variable_get('streamingvideo_button_path', 'sites/all/files'),
    '#description' => t('defaults to sites/all/files'),
  );
  $form['streamingvideo_button_file'] = array(
    '#type' => 'textfield',
    '#title' => t('Name of your js file'),
    '#default_value' => variable_get('streamingvideo_button_file', 'templates.js'),
    '#description' => t('defaults to templates.js'),
  );
  $form['info'] = array(
    '#title' => t('Next Steps'),
    '#value' => '<p>'.t('Create a file called ').variable_get('streamingvideo_button_file', 'template.js').t('(from above) and upload it to ').variable_get('streamingvideo_button_path', 'sites/all/files').t('(from above).  The file should define the names and locations of the HTML templates you would like to use in your WYSIWYG editor.  You may copy and paste the syntax from the README.txt file.').'</p>',
  );
  
  return system_settings_form($form);
}
*/
/* vim: set filetype=php : */
